- name: copy the mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install the mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: aloow remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted
      